add exit code

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -47,14 +47,17 @@ jobs:
 
       - name: Wait for DynamoDB to Start
         run: |
-          for i in {1..10}; do
+          for i in {1..15}; do
             if curl -s http://localhost:8000 > /dev/null; then
               echo "DynamoDB is up and running!"
-              break
+              exit 0
             fi
-            echo "Waiting for DynamoDB to start..."
+            echo "Waiting for DynamoDB to start... ($i)"
             sleep 2
           done
+
+          echo "DynamoDB failed to start in time." >&2
+          exit 1
 
       - name: Verify DynamoDB Local
         run: |
